/** Convert a 2-letter ISO 3166-1 alpha-2 country code to its flag emoji. */
export function toFlag(countryCode: string): string {
  return countryCode
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

/**
 * IANA timezone → ISO 3166-1 alpha-2 country code.
 * Only one representative entry per country is needed when multiple zones share it.
 * The city is extracted directly from the IANA string (last segment, underscores → spaces).
 */
const TIMEZONE_COUNTRY: Record<string, string> = {
  // ── Europe ────────────────────────────────────────────────────
  "Europe/Ljubljana":       "SI",
  "Europe/London":          "GB",
  "Europe/Dublin":          "IE",
  "Europe/Lisbon":          "PT",
  "Europe/Madrid":          "ES",
  "Europe/Paris":           "FR",
  "Europe/Brussels":        "BE",
  "Europe/Amsterdam":       "NL",
  "Europe/Berlin":          "DE",
  "Europe/Zurich":          "CH",
  "Europe/Vienna":          "AT",
  "Europe/Rome":            "IT",
  "Europe/Vatican":         "VA",
  "Europe/Monaco":          "MC",
  "Europe/Luxembourg":      "LU",
  "Europe/Copenhagen":      "DK",
  "Europe/Stockholm":       "SE",
  "Europe/Oslo":            "NO",
  "Europe/Helsinki":        "FI",
  "Europe/Tallinn":         "EE",
  "Europe/Riga":            "LV",
  "Europe/Vilnius":         "LT",
  "Europe/Warsaw":          "PL",
  "Europe/Prague":          "CZ",
  "Europe/Bratislava":      "SK",
  "Europe/Budapest":        "HU",
  "Europe/Zagreb":          "HR",
  "Europe/Belgrade":        "RS",
  "Europe/Sarajevo":        "BA",
  "Europe/Skopje":          "MK",
  "Europe/Tirane":          "AL",
  "Europe/Podgorica":       "ME",
  "Europe/Sofia":           "BG",
  "Europe/Bucharest":       "RO",
  "Europe/Athens":          "GR",
  "Europe/Nicosia":         "CY",
  "Europe/Kyiv":            "UA",
  "Europe/Minsk":           "BY",
  "Europe/Moscow":          "RU",
  "Europe/Kaliningrad":     "RU",
  "Europe/Samara":          "RU",
  "Europe/Chisinau":        "MD",
  "Europe/Istanbul":        "TR",
  "Europe/Reykjavik":       "IS",
  "Europe/Malta":           "MT",
  "Atlantic/Canary":        "ES",
  "Atlantic/Azores":        "PT",
  "Atlantic/Madeira":       "PT",
  "Atlantic/Faroe":         "FO",

  // ── Americas ──────────────────────────────────────────────────
  "America/New_York":       "US",
  "America/Chicago":        "US",
  "America/Denver":         "US",
  "America/Los_Angeles":    "US",
  "America/Anchorage":      "US",
  "America/Honolulu":       "US",
  "America/Phoenix":        "US",
  "America/Detroit":        "US",
  "America/Indiana/Indianapolis": "US",
  "America/Toronto":        "CA",
  "America/Vancouver":      "CA",
  "America/Winnipeg":       "CA",
  "America/Halifax":        "CA",
  "America/St_Johns":       "CA",
  "America/Mexico_City":    "MX",
  "America/Monterrey":      "MX",
  "America/Cancun":         "MX",
  "America/Bogota":         "CO",
  "America/Lima":           "PE",
  "America/Santiago":       "CL",
  "America/Buenos_Aires":   "AR",
  "America/Sao_Paulo":      "BR",
  "America/Manaus":         "BR",
  "America/Fortaleza":      "BR",
  "America/Caracas":        "VE",
  "America/La_Paz":         "BO",
  "America/Asuncion":       "PY",
  "America/Montevideo":     "UY",
  "America/Guayaquil":      "EC",
  "America/Guyana":         "GY",
  "America/Panama":         "PA",
  "America/Costa_Rica":     "CR",
  "America/Guatemala":      "GT",
  "America/Tegucigalpa":    "HN",
  "America/Managua":        "NI",
  "America/El_Salvador":    "SV",
  "America/Belize":         "BZ",
  "America/Jamaica":        "JM",
  "America/Havana":         "CU",
  "America/Puerto_Rico":    "PR",
  "America/Santo_Domingo":  "DO",
  "America/Port-au-Prince": "HT",

  // ── Asia ──────────────────────────────────────────────────────
  "Asia/Nicosia":           "CY",
  "Asia/Beirut":            "LB",
  "Asia/Jerusalem":         "IL",
  "Asia/Amman":             "JO",
  "Asia/Damascus":          "SY",
  "Asia/Baghdad":           "IQ",
  "Asia/Riyadh":            "SA",
  "Asia/Kuwait":            "KW",
  "Asia/Qatar":             "QA",
  "Asia/Bahrain":           "BH",
  "Asia/Dubai":             "AE",
  "Asia/Muscat":            "OM",
  "Asia/Tehran":            "IR",
  "Asia/Baku":              "AZ",
  "Asia/Yerevan":           "AM",
  "Asia/Tbilisi":           "GE",
  "Asia/Kabul":             "AF",
  "Asia/Karachi":           "PK",
  "Asia/Kolkata":           "IN",
  "Asia/Colombo":           "LK",
  "Asia/Kathmandu":         "NP",
  "Asia/Dhaka":             "BD",
  "Asia/Yangon":            "MM",
  "Asia/Bangkok":           "TH",
  "Asia/Ho_Chi_Minh":       "VN",
  "Asia/Phnom_Penh":        "KH",
  "Asia/Vientiane":         "LA",
  "Asia/Kuala_Lumpur":      "MY",
  "Asia/Singapore":         "SG",
  "Asia/Jakarta":           "ID",
  "Asia/Manila":            "PH",
  "Asia/Taipei":            "TW",
  "Asia/Hong_Kong":         "HK",
  "Asia/Macau":             "MO",
  "Asia/Shanghai":          "CN",
  "Asia/Seoul":             "KR",
  "Asia/Tokyo":             "JP",
  "Asia/Pyongyang":         "KP",
  "Asia/Ulaanbaatar":       "MN",
  "Asia/Tashkent":          "UZ",
  "Asia/Almaty":            "KZ",
  "Asia/Bishkek":           "KG",
  "Asia/Dushanbe":          "TJ",
  "Asia/Ashgabat":          "TM",
  "Asia/Yekaterinburg":     "RU",
  "Asia/Novosibirsk":       "RU",
  "Asia/Krasnoyarsk":       "RU",
  "Asia/Irkutsk":           "RU",
  "Asia/Vladivostok":       "RU",

  // ── Africa ────────────────────────────────────────────────────
  "Africa/Cairo":           "EG",
  "Africa/Tunis":           "TN",
  "Africa/Tripoli":         "LY",
  "Africa/Algiers":         "DZ",
  "Africa/Casablanca":      "MA",
  "Africa/Ceuta":           "ES",
  "Africa/Lagos":           "NG",
  "Africa/Accra":           "GH",
  "Africa/Abidjan":         "CI",
  "Africa/Dakar":           "SN",
  "Africa/Addis_Ababa":     "ET",
  "Africa/Nairobi":         "KE",
  "Africa/Dar_es_Salaam":   "TZ",
  "Africa/Kampala":         "UG",
  "Africa/Khartoum":        "SD",
  "Africa/Johannesburg":    "ZA",
  "Africa/Harare":          "ZW",
  "Africa/Maputo":          "MZ",
  "Africa/Lusaka":          "ZM",
  "Africa/Windhoek":        "NA",

  // ── Oceania ───────────────────────────────────────────────────
  "Australia/Sydney":       "AU",
  "Australia/Melbourne":    "AU",
  "Australia/Brisbane":     "AU",
  "Australia/Perth":        "AU",
  "Australia/Adelaide":     "AU",
  "Australia/Darwin":       "AU",
  "Australia/Hobart":       "AU",
  "Pacific/Auckland":       "NZ",
  "Pacific/Chatham":        "NZ",
  "Pacific/Fiji":           "FJ",
  "Pacific/Honolulu":       "US",
  "Pacific/Guam":           "GU",
  "Pacific/Port_Moresby":   "PG",
  "Pacific/Noumea":         "NC",
  "Pacific/Tahiti":         "PF",
  "Pacific/Apia":           "WS",
  "Pacific/Tongatapu":      "TO",
};

/**
 * Format an IANA timezone string as "🇸🇮 Ljubljana".
 * Falls back to the raw city segment if the timezone is not in the map.
 */
export function formatTimezone(tz: string): string {
  const city = tz.split("/").pop()?.replace(/_/g, " ") ?? tz;
  const countryCode = TIMEZONE_COUNTRY[tz];
  if (!countryCode) return city;
  return `${toFlag(countryCode)} ${city}`;
}